name: Sync branches with conflict handling

on:
  push:
    branches:
      - '*'

jobs:
  branch-sync:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CHAT_WEBHOOK_URL: "https://chat.googleapis.com/v1/spaces/AAAAiN5o6yI/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=V37-y3Z6RgoenZeoHilnzBw9xmYPEI_O0e33MhaqvQA"
      GH_TOKEN: ${{ secrets.JEGANMERGE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up git
        run: |
          COMMITTER_NAME=$(git log -1 --pretty=format:'%an')
          COMMITTER_EMAIL=$(git log -1 --pretty=format:'%ae')
          
          git config --global user.name "$COMMITTER_NAME"
          git config --global user.email "$COMMITTER_EMAIL"
          
          echo "Configured git with user.name=$COMMITTER_NAME and user.email=$COMMITTER_EMAIL"

      - name: Define wait_for_pr_merge function
        run: |
          wait_for_pr_merge() {
            local pr_number=$1
            local branch_name=$2
            local target_branch=$3
            local merged_message=$4

            echo "Waiting for PR #$pr_number to be merged..."

            while true; do
              pr_status=$(gh pr view "$pr_number" --json state -q ".state")
              echo "Current PR status: $pr_status"
              if [ "$pr_status" == "MERGED" ]; then
                curl -X POST -H 'Content-Type: application/json' --data "{\"text\": \"$merged_message\"}" "$GOOGLE_CHAT_WEBHOOK_URL"
                break
              elif [ "$pr_status" == "CLOSED" ] || [ "$pr_status" == "DRAFT" ]; then
                echo "PR #$pr_number is not merged yet or is in an unexpected state. Exiting."
                exit 1
              fi
              sleep 30
            done
          }

      - name: Determine branch type and process accordingly
        id: determine_branches
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          echo "Branch name: $branch_name"

          case "$branch_name" in
            profit_dep_hf_*)
              BRANCH_TYPE="hf"
              ;;
            profit_dep_minor_*)
              BRANCH_TYPE="minor"
              ;;
            *)
              BRANCH_TYPE="none"
              ;;
          esac

          echo "Branch Type: $BRANCH_TYPE"

          if [ "$BRANCH_TYPE" == "hf" ]; then
            latest_minor_branch=$(git branch -r | grep 'origin/profit_dep_minor_' | sed 's/origin\///' | sort -r | head -n 1 | xargs)
            echo "Latest minor branch: $latest_minor_branch"

            git fetch --all
            git checkout $latest_minor_branch
            git merge --no-commit --no-ff origin/$branch_name || true
            if git ls-files -u | grep -q .; then
              echo "Merge conflict detected."
              conflict_files=$(git diff --name-only --diff-filter=U | awk '{print " - " $0}' | tr '\n' '\n')
              committer=$(git log -1 --pretty=format:'%an')
              
              message="Merge conflict detected when merging HF into minor.\nConflicting files:\n$conflict_files\nLast committer: $committer"
              curl -X POST -H 'Content-Type: application/json' --data "{\"text\": \"$message\"}" "$GOOGLE_CHAT_WEBHOOK_URL"
              exit 1
            fi
            git checkout $branch_name

            curl -X POST -H 'Content-Type: application/json' --data "{\"text\": \"Preparing to create PR: $branch_name into $latest_minor_branch\"}" "$GOOGLE_CHAT_WEBHOOK_URL"

            pr_url=$(gh pr create \
              --title "Merge $branch_name into $latest_minor_branch" \
              --body "This PR merges the changes from $branch_name into $latest_minor_branch." \
              --base "$latest_minor_branch" \
              --head "$branch_name" )
            
            echo "PR URL: $pr_url"
            pr_number=$(basename "$pr_url")

            wait_for_pr_merge "$pr_number" "$branch_name" "$latest_minor_branch" "Merged $branch_name into $latest_minor_branch up to date. Now proceeding to create PR from Minor to Master."

          elif [ "$BRANCH_TYPE" == "minor" ]; then
            git fetch --all
            git checkout master
            git merge --no-commit --no-ff origin/$branch_name || true
            if git ls-files -u | grep -q .; then
              echo "Merge conflict detected."
              conflict_files=$(git diff --name-only --diff-filter=U | awk '{print " - " $0}' | tr '\n' '\n')
              committer=$(git log -1 --pretty=format:'%an')
              
              message="Merge conflict detected when merging minor into master.\nConflicting files:\n$conflict_files\nLast committer: $committer"
              curl -X POST -H 'Content-Type: application/json' --data "{\"text\": \"$message\"}" "$GOOGLE_CHAT_WEBHOOK_URL"
              exit 1
            fi
            git checkout $branch_name

            curl -X POST -H 'Content-Type: application/json' --data "{\"text\": \"Preparing to create PR: $branch_name into master\"}" "$GOOGLE_CHAT_WEBHOOK_URL"

            pr_url=$(gh pr create \
              --title "Merge $branch_name into master" \
              --body "This PR merges the changes from $branch_name into master." \
              --base master \
              --head "$branch_name" )
            
            echo "PR URL: $pr_url"
            pr_number=$(basename "$pr_url")

            wait_for_pr_merge "$pr_number" "$branch_name" "master" "Merged $branch_name into master up to date."
          fi
