name: Example Workflow

on:
  push:
    branches:
      - 'main'

jobs:
  example:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.JEGANMERGE }}  # Use the secret name you set

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up GitHub CLI
        run: |
          gh auth login --with-token <<< "${JEGAN}"  # Use the environment variable

      - name: Create Pull Request
        run: |
          gh pr create --title "Example PR" --body "This is an example PR" --base main --head feature-branch
