name: Sync branches with conflict handling

on:
  push:
    branches:
      - '*'

jobs:
  branch-sync:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CHAT_WEBHOOK_URL: "https://chat.googleapis.com/v1/spaces/AAAAiN5o6yI/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=V37-y3Z6RgoenZeoHilnzBw9xmYPEI_O0e33MhaqvQA"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up git
        run: |
          COMMITTER_NAME=$(git log -1 --pretty=format:'%an')
          COMMITTER_EMAIL=$(git log -1 --pretty=format:'%ae')
          
          git config --global user.name "$COMMITTER_NAME"
          git config --global user.email "$COMMITTER_EMAIL"
          
          echo "Configured git with user.name=$COMMITTER_NAME and user.email=$COMMITTER_EMAIL"
      - name: Check if direct commit to master
        id: check_direct_commit
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          
          if [ "$branch_name" == "master" ]; then
            echo "Direct commit to master detected."
            echo "DIRECT_COMMIT=true" >> $GITHUB_ENV
          else
            echo "DIRECT_COMMIT=false" >> $GITHUB_ENV
          fi
      - name: Determine branch type
        id: determine_branches
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          
          case "$branch_name" in
            profit_dep_hf_*)
              echo "BRANCH_TYPE=hf" >> $GITHUB_ENV
              ;;
            profit_dep_minor_*)
              echo "BRANCH_TYPE=minor" >> $GITHUB_ENV
              ;;
            *)
              echo "BRANCH_TYPE=none" >> $GITHUB_ENV
              ;;
          esac
          
          echo "Branch Type: $BRANCH_TYPE"
      - name: Fetch and merge branches based on type
        if: env.DIRECT_COMMIT == 'false'
        run: |
          git fetch origin
          branch_name="${GITHUB_REF#refs/heads/}"
          BRANCH_TYPE="${{ steps.determine_branches.outputs.BRANCH_TYPE }}"
          
          if [ "$BRANCH_TYPE" == "hf" ]; then
            latest_minor_branch=$(git branch -r | grep 'origin/profit_dep_minor_' | sed 's/origin\///' | sort -r | head -n 1 | xargs)
            echo "Latest minor branch: $latest_minor_branch"
            
            git checkout $latest_minor_branch
            git merge --no-commit --no-ff origin/$branch_name || true
            
            if git ls-files -u | grep -q .; then
              echo "Merge conflict detected."
              conflict_files=$(git diff --name-only --diff-filter=U | awk '{print " - " $0}' | tr '\n' '\n')
              committer=$(git log -1 --pretty=format:'%an')
              
              message="Merge conflict detected when merging HF into minor.\nConflicting files:\n$conflict_files\nLast committer: $committer"
              curl -X POST -H 'Content-Type: application/json' --data "{\"text\": \"$message\"}" "$GOOGLE_CHAT_WEBHOOK_URL"
              
              exit 1
            fi
            git commit -m "Merge $branch_name into $latest_minor_branch"
            git push origin $latest_minor_branch
            echo "PR_TYPE=hf_to_minor" >> $GITHUB_ENV
            echo "PR_URL=$(gh pr list --state open --head $branch_name --base $latest_minor_branch --json url --jq '.[0].url')" >> $GITHUB_ENV
          elif [ "$BRANCH_TYPE" == "minor" ]; then
            git checkout master
            git merge --no-commit --no-ff origin/$branch_name || true
            
            if git ls-files -u | grep -q .; then
              echo "Merge conflict detected."
              conflict_files=$(git diff --name-only --diff-filter=U | awk '{print " - " $0}' | tr '\n' '\n')
              committer=$(git log -1 --pretty=format:'%an')
              
              message="Merge conflict detected when merging minor into master.\nConflicting files:\n$conflict_files\nLast committer: $committer"
              curl -X POST -H 'Content-Type: application/json' --data "{\"text\": \"$message\"}" "$GOOGLE_CHAT_WEBHOOK_URL"
              
              exit 1
            fi
            git commit -m "Merge $branch_name into master"
            git push origin master
            echo "PR_TYPE=minor_to_master" >> $GITHUB_ENV
            echo "PR_URL=$(gh pr list --state open --head $branch_name --base master --json url --jq '.[0].url')" >> $GITHUB_ENV
          fi
      - name: Create PR from HF to Minor
        if: env.BRANCH_TYPE == 'hf'
        id: create_hf_to_minor_pr
        env:
          GH_TOKEN: ${{ secrets.JEGANMERGE }}
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          latest_minor_branch=$(git branch -r | grep 'origin/profit_dep_minor_' | sed 's/origin\///' | sort -r | head -n 1 | xargs)
          
          echo "Creating PR from $branch_name to $latest_minor_branch"
          pr_url=$(gh pr create \
            --title "Merge $branch_name into $latest_minor_branch" \
            --body "This PR merges the changes from $branch_name into $latest_minor_branch." \
            --base "$latest_minor_branch" \
            --head "$branch_name" )
          
          echo "PR URL: $pr_url"
          curl -X POST -H 'Content-Type: application/json' --data "{\"text\": \"Pull request created: $pr_url\"}" "$GOOGLE_CHAT_WEBHOOK_URL"
      - name: Create PR from Minor to Master
        if: env.BRANCH_TYPE == 'minor'
        id: create_minor_to_master_pr
        env:
          GH_TOKEN: ${{ secrets.JEGANMERGE }}
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          
          echo "Creating PR from $branch_name to master"
          pr_url=$(gh pr create \
            --title "Merge $branch_name into master" \
            --body "This PR merges the changes from $branch_name into master." \
            --base master \
            --head "$branch_name" )
          
          echo "PR URL: $pr_url"
          curl -X POST -H 'Content-Type: application/json' --data "{\"text\": \"Pull request created: $pr_url\"}" "$GOOGLE_CHAT_WEBHOOK_URL"
      - name: Wait for PR Merge and Notify
        if: env.PR_TYPE == 'hf_to_minor'
        uses: actions/github-script@v6
        with:
          script: |
            const prUrl = process.env.PR_URL;
            if (!prUrl) {
              console.error('PR URL is missing');
              process.exit(1);
            }
            
            let prMerged = false;
            while (!prMerged) {
              const { data: pr } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prUrl.split('/').pop()
              });
              
              if (pr.state === 'closed' && pr.merged) {
                prMerged = true;
                await github.rest.repos.createDispatchEvent({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  event_type: 'hf_minor_merged'
                });
              } else {
                console.log('Waiting for PR to be merged...');
                await new Promise(resolve => setTimeout(resolve, 60000)); // Wait for 1 minute
              }
            }
      - name: Wait for Minor to Master PR Merge and Notify
        if: env.PR_TYPE == 'minor_to_master'
        uses: actions/github-script@v6
        with:
          script: |
            const prUrl = process.env.PR_URL;
            if (!prUrl) {
              console.error('PR URL is missing');
              process.exit(1);
            }
            
            let prMerged = false;
            while (!prMerged) {
              const { data: pr } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prUrl.split('/').pop()
              });
              
              if (pr.state === 'closed' && pr.merged) {
                prMerged = true;
                await github.rest.repos.createDispatchEvent({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  event_type: 'minor_master_merged'
                });
              } else {
                console.log('Waiting for PR to be merged...');
                await new Promise(resolve => setTimeout(resolve, 60000)); // Wait for 1 minute
              }
            }
      - name: Notify Google Chat on HF to Minor Merge
        if: github.event_name == 'repository_dispatch' && github.event.action == 'hf_minor_merged'
        run: |
          curl -X POST -H 'Content-Type: application/json' --data '{"text": "Successfully merged HF into Minor."}' "$GOOGLE_CHAT_WEBHOOK_URL"
      - name: Notify Google Chat on Minor to Master Merge
        if: github.event_name == 'repository_dispatch' && github.event.action == 'minor_master_merged'
        run: |
          curl -X POST -H 'Content-Type: application/json' --data '{"text": "Successfully merged Minor into Master."}' "$GOOGLE_CHAT_WEBHOOK_URL"
