name: List and Deploy PR Changed Files

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  list-files:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.check.outputs.changed_files }}  # Define output

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Get PR number and check changed files
        id: check
        env:
          GH_TOKEN: ${{ secrets.JEGANMERGE }}  # Set the GitHub token for gh authentication
        run: |
          pr_number=${{ github.event.pull_request.number }}
          changed_files=$(gh pr view $pr_number --json files --jq '.files[].path')
          changed_files_single_line=$(echo "$changed_files" | tr '\n' ' ')
          echo "changed_files=$changed_files_single_line" >> $GITHUB_ENV
          echo "::set-output name=changed_files::$changed_files_single_line"  # Set the output
          # Output the changed files for logging
          echo "Changed files:"
          echo "$changed_files_single_line"

  deploy:
    runs-on: ubuntu-latest
    needs: list-files

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files from previous step
        id: get_changed_files
        run: |
          changed_files="${{ needs.list-files.outputs.changed_files }}"  # Access output from the previous job
          echo "Changed files: $changed_files"
          echo "$changed_files" > changed_files.txt

      - name: Check if changed files are present
        run: |
          if [ -s changed_files.txt ]; then
            echo "Changed files detected, proceeding with deployment."
          else
            echo "No changed files found, skipping deployment."
            exit 0  # Exit early if no files to deploy
          fi

      - name: Deploy Changed Files to Remote Server
        if: success() && needs.list-files.outputs.changed_files != ''  # Ensure this checks the variable correctly
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          GIT_PATH: "/home/jegan/git-rsync-en"
          DEPLOY_PATH: "/home/jegan/www_profitokrs_com_6_4_1"
          BACKUP_PATH: "/home/jegan/profit-site-en-backup"
        run: |
          changed_files="${{ needs.list-files.outputs.changed_files }}"  # Correctly access it as output
          if [ -z "$changed_files" ]; then
            echo "No files to deploy."
            exit 0  # Exit if there are no files to deploy
          fi
          files=($changed_files)
          DATE=$(date +%F-%H-%M)
          echo "Number of Files = ${#files[@]}"
          echo " "
          for file in "${files[@]}"; do
              if ssh $REMOTE_USER@$REMOTE_HOST "[ -f '$DEPLOY_PATH/$file' ]"; then
                  echo "Backing up $DEPLOY_PATH/$file"
                  ssh $REMOTE_USER@$REMOTE_HOST "sudo cp -r '$DEPLOY_PATH/$file' '$BACKUP_PATH/$file-bak-$DATE'"
              fi
              echo "Deploying $file to $REMOTE_HOST"
              scp -o StrictHostKeyChecking=no "$GIT_PATH/$file" "$REMOTE_USER@$REMOTE_HOST:$DEPLOY_PATH/$file"
              ssh $REMOTE_USER@$REMOTE_HOST "sudo chown -R www-data: '$DEPLOY_PATH/$file'; sudo chmod 640 '$DEPLOY_PATH/$file'"
              echo "$file deployed successfully"
          done
