name: List Latest Files

on:
  push:
    branches:
      - develop
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: List latest files merged into develop
        run: |
          # Fetch the merge commit information
          git fetch --prune --unshallow
          
          # Check if the last commit is a merge commit
          if [ $(git rev-parse --verify HEAD) ]; then
            latest_merge_commit=$(git log -1 --merges --pretty=format:"%H")
            
            # If there's a latest merge commit, list files changed
            if [ -n "$latest_merge_commit" ]; then
              echo "Files changed in the latest merge commit ($latest_merge_commit):"
              git diff-tree --no-commit-id --name-only -r $latest_merge_commit
            else
              echo "No merge commits found."
            fi
          else
            echo "No commits in the current branch."
          fi
