name: Test Secrets

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Secrets
        run: |
          echo "REMOTE_USER: ${{ secrets.REMOTE_USER }}"
          echo "REMOTE_HOST: ${{ secrets.REMOTE_HOST }}"
